// eslint-disable-next-line import/no-named-default
import { default as DefaultContractsAddresses } from '@oceanprotocol/contracts/addresses/address.json'
import fs from 'fs'
import { Config } from '.'
import { LoggerInstance } from '../utils/Logger.js'

const configHelperNetworksBase: Config = {
  chainId: null,
  network: 'unknown',
  nodeUri: 'http://127.0.0.1:8545',
  oceanNodeUri: 'https://1.c2d.nodes.oceanprotocol.com:8000/',
  explorerUri: null,
  oceanTokenAddress: null,
  oceanTokenSymbol: 'OCEAN',
  fixedRateExchangeAddress: null,
  dispenserAddress: null,
  startBlock: 0,
  transactionBlockTimeout: 50,
  transactionConfirmationBlocks: 1,
  transactionPollingTimeout: 750,
  gasFeeMultiplier: 1
}

export const configHelperNetworks: Config[] = [
  {
    ...configHelperNetworksBase
  },
  {
    // barge
    ...configHelperNetworksBase,
    chainId: 8996,
    network: 'development',
    oceanNodeUri: 'https://1.c2d.nodes.oceanprotocol.com:8000/',
    sdk: 'evm'
  },
  {
    ...configHelperNetworksBase,
    chainId: 11155111,
    network: 'sepolia',
    nodeUri: 'https://sepolia.infura.io/v3',
    explorerUri: 'https://sepolia.etherscan.io',
    gasFeeMultiplier: 1.1,
    sdk: 'evm'
  },
  {
    ...configHelperNetworksBase,
    chainId: 1,
    network: 'mainnet',
    nodeUri: 'https://mainnet.infura.io/v3',
    explorerUri: 'https://etherscan.io',
    startBlock: 11105459,
    transactionBlockTimeout: 150,
    transactionConfirmationBlocks: 5,
    transactionPollingTimeout: 1750,
    gasFeeMultiplier: 1.05,
    sdk: 'evm'
  },
  {
    ...configHelperNetworksBase,
    chainId: 137,
    network: 'polygon',
    nodeUri: 'https://polygon-mainnet.infura.io/v3',
    explorerUri: 'https://polygonscan.com',
    oceanTokenSymbol: 'mOCEAN',
    gasFeeMultiplier: 1.6,
    sdk: 'evm'
  },
  {
    ...configHelperNetworksBase,
    chainId: 2021000,
    network: 'gaiaxtestnet',
    nodeUri: 'https://rpc.gaiaxtestnet.oceanprotocol.com',
    explorerUri: 'https://blockscout.gaiaxtestnet.oceanprotocol.com',
    sdk: 'evm'
  },
  {
    ...configHelperNetworksBase,
    chainId: 80001,
    network: 'mumbai',
    nodeUri: 'https://polygon-mumbai.infura.io/v3',
    explorerUri: 'https://mumbai.polygonscan.com',
    gasFeeMultiplier: 1.1,
    sdk: 'evm'
  },
  {
    ...configHelperNetworksBase,
    chainId: 56,
    network: 'bsc',
    nodeUri: 'https://bsc-dataseed.binance.org',
    explorerUri: 'https://bscscan.com/',
    gasFeeMultiplier: 1.05,
    sdk: 'evm'
  },
  {
    ...configHelperNetworksBase,
    chainId: 246,
    network: 'energyweb',
    nodeUri: 'https://rpc.energyweb.org',
    explorerUri: 'https://explorer.energyweb.org',
    gasFeeMultiplier: 1.05,
    sdk: 'evm'
  },
  {
    ...configHelperNetworksBase,
    chainId: 1285,
    network: 'moonriver',
    nodeUri: 'https://moonriver.api.onfinality.io/public',
    explorerUri: 'https://moonriver.moonscan.io/',
    gasFeeMultiplier: 1.05,
    sdk: 'evm'
  },
  {
    ...configHelperNetworksBase,
    chainId: 100,
    network: 'gen-x-testnet',
    nodeUri: 'https://rpc.genx.minimal-gaia-x.eu',
    explorerUri: 'https://explorer.genx.minimal-gaia-x.eu/',
    gasFeeMultiplier: 1,
    sdk: 'evm'
  },
  {
    ...configHelperNetworksBase,
    chainId: 10,
    network: 'optimism',
    nodeUri: 'https://mainnet.optimism.io',
    explorerUri: 'https://optimistic.etherscan.io/',
    gasFeeMultiplier: 1.1,
    sdk: 'evm'
  },
  {
    ...configHelperNetworksBase,
    chainId: 11155420,
    network: 'optimism_sepolia',
    nodeUri: 'https://sepolia.optimism.io',
    explorerUri: 'https://sepolia-optimism.etherscan.io/',
    gasFeeMultiplier: 1.1,
    sdk: 'evm'
  },
  {
    ...configHelperNetworksBase,
    chainId: 23294,
    network: 'oasis_sapphire',
    nodeUri: 'https://sapphire.oasis.io',
    explorerUri: 'https://explorer.oasis.io/mainnet/sapphire/',
    gasFeeMultiplier: 1,
    sdk: 'oasis'
  },
  {
    ...configHelperNetworksBase,
    chainId: 23295,
    network: 'oasis_sapphire_testnet',
    nodeUri: 'https://testnet.sapphire.oasis.dev',
    explorerUri: 'https://explorer.oasis.io/testnet/sapphire/',
    gasFeeMultiplier: 1,
    sdk: 'oasis'
  },
  {
    ...configHelperNetworksBase,
    chainId: 32456,
    network: 'pontus-x-devnet',
    nodeUri: 'https://rpc.dev.pontus-x.eu',
    explorerUri: 'https://explorer.dev.pontus-x.eu/testnet/pontusx',
    sdk: 'evm'
  }
]

export const KNOWN_CONFIDENTIAL_EVMS = [
  23294, // oasis_sapphire
  23295 // oasis_sapphire_testnet
]

export class ConfigHelper {
  /* Load contract addresses from env ADDRESS_FILE (generated by ocean-contracts) */
  public getAddressesFromEnv(network: string, customAddresses?: any): Partial<Config> {
    let configAddresses: Partial<Config>

    const getUris = () => {
      if (process.env.OCEAN_NODE_URL) {
        return {
          oceanNodeUri: process.env.OCEAN_NODE_URL
        }
      }
      return {}
    }

    if (customAddresses && customAddresses[network]) {
      const {
        FixedPrice,
        Dispenser,
        ERC721Factory,
        OPFCommunityFeeCollector,
        Ocean,
        chainId,
        startBlock,
        veAllocate,
        veOCEAN,
        veDelegation,
        veFeeDistributor,
        veDelegationProxy,
        DFRewards,
        DFStrategyV1,
        veFeeEstimate,
        Router,
        AccessListFactory
      } = customAddresses[network]
      configAddresses = {
        nftFactoryAddress: ERC721Factory,
        opfCommunityFeeCollector: OPFCommunityFeeCollector,
        fixedRateExchangeAddress: FixedPrice,
        dispenserAddress: Dispenser,
        oceanTokenAddress: Ocean,
        routerFactoryAddress: Router,
        chainId,
        startBlock,
        veAllocate,
        veOCEAN,
        veDelegation,
        veFeeDistributor,
        veDelegationProxy,
        DFRewards,
        DFStrategyV1,
        veFeeEstimate,
        accessListFactory: AccessListFactory,
        ...getUris()
      }
    } else if ((DefaultContractsAddresses as { [key: string]: any })[network]) {
      const {
        FixedPrice,
        Dispenser,
        OPFCommunityFeeCollector,
        ERC721Factory,
        Ocean,
        chainId,
        startBlock,
        veAllocate,
        veOCEAN,
        veDelegation,
        veFeeDistributor,
        veDelegationProxy,
        DFRewards,
        DFStrategyV1,
        veFeeEstimate,
        Router,
        AccessListFactory
      } = (DefaultContractsAddresses as { [key: string]: any })[network]
      configAddresses = {
        nftFactoryAddress: ERC721Factory,
        opfCommunityFeeCollector: OPFCommunityFeeCollector,
        fixedRateExchangeAddress: FixedPrice,
        dispenserAddress: Dispenser,
        oceanTokenAddress: Ocean,
        routerFactoryAddress: Router,
        chainId,
        startBlock,
        veAllocate,
        veOCEAN,
        veDelegation,
        veFeeDistributor,
        veDelegationProxy,
        DFRewards,
        DFStrategyV1,
        veFeeEstimate,
        accessListFactory: AccessListFactory,
        ...getUris()
      }
    }
    return configAddresses
  }

  /**
   * Returns the config object for a specific network supported by the oceanprotocol stack
   * @param {string | number} network the network's chainId or name
   * @param {string} infuraProjectId optional infura project id that will replace the configs node URI
   * @return {Config} Config obhjedct
   */
  public getConfig(network: string | number, infuraProjectId?: string): Config {
    const filterBy = typeof network === 'string' ? 'network' : 'chainId'

    let config = configHelperNetworks.find((c) => c[filterBy] === network)

    if (!config) {
      LoggerInstance.error(`No config found for given network '${network}'`)
      return null
    }

    let addresses
    try {
      addresses = process.env.ADDRESS_FILE
        ? JSON.parse(
            // eslint-disable-next-line security/detect-non-literal-fs-filename
            fs.readFileSync(process.env.ADDRESS_FILE, 'utf8')
          )
        : null
    } catch (e) {
      console.log(e)
      addresses = null
    }

    let contractAddressesConfig = this.getAddressesFromEnv(config.network, addresses)
    // check oasis network name typos on addresses.json
    if (!contractAddressesConfig && KNOWN_CONFIDENTIAL_EVMS.includes(config.chainId)) {
      contractAddressesConfig = this.getAddressesFromEnv(
        config.network.replace('sapph', 'saph'),
        addresses
      )
    }

    if (!('sdk' in config) || config.sdk === null) {
      if (KNOWN_CONFIDENTIAL_EVMS.includes(config.chainId)) {
        config.sdk = 'oasis'
      } else {
        config.sdk = 'evm'
      }
    }
    if (contractAddressesConfig && 'accessListFactory' in contractAddressesConfig) {
      config.accessListFactory = contractAddressesConfig.accessListFactory
    }

    config = { ...config, ...contractAddressesConfig }

    const nodeUri = infuraProjectId
      ? `${config.nodeUri}/${infuraProjectId}`
      : config.nodeUri

    return { ...config, nodeUri }
  }
}
